### ISSUE TITLE
value of vmware_host_boot_timestamp_seconds doesn't get updated

### ISSUE THREAD

**Issue by lijun1234** [devinotelecom/prometheus-vmware-exporter#15]
Like your esxi exporter becuase it works on standalone esxi host without vcenter. 
Notice 1 issue not sure if just me or actually a bug need to fix.
The issue:
  Host boot up second not updated
Env: 
  Prometheus 2.23.0 on Ubuntu 20.04 collecting metrics from standalone esxi hosts version from v5.5, v6.0 and v6.5
Reproduce:
  Query vmware_host_boot_timestamp_seconds as # HELP vmware_host_boot_timestamp_seconds Uptime host
   After 1 hour query again the output doesn't change at all.
   Try different hosts with different ESXI version all same.
Notes:
  Other metrics related to cpu, ram datastore and vm are good. 

If issue doesn't happen on your end, could you please provide the trouble shooting steps so I can try to fix it.

Thank you.

**Comment by avojak** [comment]
I was wondering the same thing, until I realized that it's not _really_ the uptime like the `HELP` comment implies - it's the timestamp when the host was booted. So uptime would be `now - vmware_host_boot_timestamp_seconds`
