### ISSUE TITLE
Wrong conversion factor in metrics.go

### ISSUE THREAD

**Issue by fchiacchiaretta** [devinotelecom/prometheus-vmware-exporter#3]
Hi,
I think I found a wrong conversion factor on line 229 in metrics.go
https://github.com/devinotelecom/prometheus-vmware-exporter/blob/4cdedb2b6524cad9f6ad8bbfaf425407a4413f08/controller/metrics.go#L229

The last number should be 1024 not 1204, shouldn't it?

Best,
Federico Chiacchiaretta

**Comment by magna-z** [comment]
Thanks, @fchiacchiaretta!

This is error, and will be fixed in PR #5.
